/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package p5compendium_luismontalvan;

import java.util.ArrayList;
/**
 *
 * @author luism
 */
public class P5Compendium_LuisMontalvan {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        //Informe sobre el avance
        //No hay mucho en este avance ademas la interfaz basica del programa que es probablemente lo mas largo y tedioso
        //Al ejecutar saldra la lista completa de personas en el compendium de Persona 5 Royal
        //Tengo pensado ademas de mostar cada persona poder convocarlos y almacenar un total de 6 y tambien borrar personas si asi lo desea el usuario
        //Otra cosa que tengo pensado implementar es que otra condicion para convocar personas es tener el dinero suficiente (en yenes o dolares dependiendo si java soporta los caracteres)
        //El usuario empezaria con alrededor de un millon de yenes y el valor de cada persona estaria en el rango de 2000 a 300000 yenes por cada uno
        //Me comenta porfavor si la complejidad del proyecto esta bien o si deberia añadir algunas cosas para mejorarlo
        ArrayList nivel= new ArrayList();
        nivel.add(1);
        nivel.add(2);
        nivel.add(2);
        nivel.add(3);
        nivel.add(3);
        nivel.add(4);
        nivel.add(5);
        nivel.add(5);
        nivel.add(6);
        nivel.add(6);
        nivel.add(6);
        nivel.add(7);
        nivel.add(7);
        nivel.add(8);
        nivel.add(9);
        nivel.add(9);
        nivel.add(9);
        nivel.add(9);
        nivel.add(9);
        nivel.add(10);
        nivel.add(10);
        nivel.add(11);
        nivel.add(11);
        nivel.add(11);
        nivel.add(11);
        nivel.add(11);
        nivel.add(12);
        nivel.add(12);
        nivel.add(13);
        nivel.add(13);
        nivel.add(13);
        nivel.add(14);
        nivel.add(14);
        nivel.add(15);
        nivel.add(15);
        nivel.add(15);
        nivel.add(16);
        nivel.add(16);
        nivel.add(16);
        nivel.add(16);
        nivel.add(17);
        nivel.add(17);
        nivel.add(17);
        nivel.add(17);
        nivel.add(18);
        nivel.add(18);
        nivel.add(19);
        nivel.add(19);
        nivel.add(20);
        nivel.add(20);
        nivel.add(20);
        nivel.add(20);
        nivel.add(20);
        nivel.add(21);
        nivel.add(21);
        nivel.add(22);
        nivel.add(22);
        nivel.add(23);
        nivel.add(23);
        nivel.add(23);
        nivel.add(24);
        nivel.add(24);
        nivel.add(24);
        nivel.add(25);
        nivel.add(25);
        nivel.add(25);
        nivel.add(25);
        nivel.add(25);
        nivel.add(26);
        nivel.add(26);
        nivel.add(26);
        nivel.add(26);
        nivel.add(27);
        nivel.add(27);
        nivel.add(27);
        nivel.add(28);
        nivel.add(28);
        nivel.add(29);
        nivel.add(29);
        nivel.add(30);
        nivel.add(30);
        nivel.add(30);
        nivel.add(30);
        nivel.add(31);
        nivel.add(31);
        nivel.add(32);
        nivel.add(32);
        nivel.add(33);
        nivel.add(33);
        nivel.add(34);
        nivel.add(34);
        nivel.add(35);
        nivel.add(35);
        nivel.add(35);
        nivel.add(36);
        nivel.add(36);
        nivel.add(37);
        nivel.add(37);
        nivel.add(38);
        nivel.add(38);
        nivel.add(39);
        nivel.add(39);
        nivel.add(39);
        nivel.add(40);
        nivel.add(40);
        nivel.add(40);
        nivel.add(40);
        nivel.add(41);
        nivel.add(41);
        nivel.add(42);
        nivel.add(42);
        nivel.add(42);
        nivel.add(42);
        nivel.add(42);
        nivel.add(43);
        nivel.add(43);
        nivel.add(43);
        nivel.add(44);
        nivel.add(44);
        nivel.add(44);
        nivel.add(45);
        nivel.add(45);
        nivel.add(46);
        nivel.add(46);
        nivel.add(47);
        nivel.add(48);
        nivel.add(48);
        nivel.add(48);
        nivel.add(49);
        nivel.add(49);
        nivel.add(50);
        nivel.add(50);
        nivel.add(50);
        nivel.add(50);
        nivel.add(50);
        nivel.add(51);
        nivel.add(51);
        nivel.add(52);
        nivel.add(52);
        nivel.add(52);
        nivel.add(52);
        nivel.add(53);
        nivel.add(53);
        nivel.add(54);
        nivel.add(54);
        nivel.add(55);
        nivel.add(55);
        nivel.add(55);
        nivel.add(56);
        nivel.add(56);
        nivel.add(56);
        nivel.add(57);
        nivel.add(58);
        nivel.add(58);
        nivel.add(59);
        nivel.add(59);
        nivel.add(60);
        nivel.add(60);
        nivel.add(60);
        nivel.add(61);
        nivel.add(62);
        nivel.add(62);
        nivel.add(62);
        nivel.add(63);
        nivel.add(63);
        nivel.add(64);
        nivel.add(64);
        nivel.add(64);
        nivel.add(65);
        nivel.add(65);
        nivel.add(66);
        nivel.add(66);
        nivel.add(67);
        nivel.add(67);
        nivel.add(68);
        nivel.add(68);
        nivel.add(69);
        nivel.add(69);
        nivel.add(70);
        nivel.add(70);
        nivel.add(71);
        nivel.add(72);
        nivel.add(72);
        nivel.add(73);
        nivel.add(73);
        nivel.add(74);
        nivel.add(74);
        nivel.add(75);
        nivel.add(75);
        nivel.add(76);
        nivel.add(76);
        nivel.add(76);
        nivel.add(76);
        nivel.add(77);
        nivel.add(77);
        nivel.add(78);
        nivel.add(80);
        nivel.add(80);
        nivel.add(80);
        nivel.add(80);
        nivel.add(81);
        nivel.add(81);
        nivel.add(81);
        nivel.add(82);
        nivel.add(82);
        nivel.add(82);
        nivel.add(82);
        nivel.add(83);
        nivel.add(83);
        nivel.add(83);
        nivel.add(83);
        nivel.add(84);
        nivel.add(84);
        nivel.add(84);
        nivel.add(84);
        nivel.add(85);
        nivel.add(85);
        nivel.add(86);
        nivel.add(86);
        nivel.add(87);
        nivel.add(87);
        nivel.add(87);
        nivel.add(88);
        nivel.add(89);
        nivel.add(89);
        nivel.add(89);
        nivel.add(90);
        nivel.add(90);
        nivel.add(92);
        nivel.add(93);
        nivel.add(93);
        nivel.add(95);
        ArrayList name = new ArrayList();
        name.add("Arsene                    |");
        name.add("Jack-o'-Lantern           |");
        name.add("Pixie                     |");
        name.add("Agathion                  |");
        name.add("Mandrake                  |");
        name.add("Bicorn                    |");
        name.add("Cait Sith                 |");
        name.add("Incubus                   |");
        name.add("Kelpie                    |");
        name.add("Saki Mitama               |");
        name.add("Silky                     |");
        name.add("Genbu                     |");
        name.add("Succubus                  |");
        name.add("Obariyon                  |");
        name.add("Angel                     |");
        name.add("Berith                    |");
        name.add("Hua Po                    |");
        name.add("Koropokkuru               |");
        name.add("Mokoi                     |");
        name.add("Regent                    |");
        name.add("Slime                     |");
        name.add("Asparas                   |");
        name.add("Jack Frost                |");
        name.add("Kodama                    |");
        name.add("Koppa Tengu               |");
        name.add("Orpheus F                 |");
        name.add("Kushi Mitama              |");
        name.add("Onmoraki                  |");
        name.add("Ame-no-Uzume              |");
        name.add("Ippon-Datara              |");
        name.add("Orpheus F Picaro          |");
        name.add("Archangel                 |");
        name.add("Inugami                   |");
        name.add("Makami                    |");
        name.add("Queen's Necklace          |");
        name.add("Shiisaa                   |");
        name.add("Eligor                    |");
        name.add("High Pixie                |");
        name.add("Suzaku                    |");
        name.add("Kaguya                    |");
        name.add("Matador                   |");
        name.add("Nekomata                  |");
        name.add("Orobas                    |");
        name.add("Sudama                    |");
        name.add("Black Ooze                |");
        name.add("Shiki-Ouji                |");
        name.add("Flauros                   |");
        name.add("Leanan Sidhe              |");
        name.add("Nue                       |");
        name.add("Oni                       |");
        name.add("Stone of Scone            |");
        name.add("Yaksini                   |");
        name.add("Izanagi                   |");
        name.add("Orthrus                   |");
        name.add("Pheonix                   |");
        name.add("Jikokuten                 |");  
        name.add("Nigi Mitama               |");
        name.add("Fuu-ki                    |");
        name.add("Sandman                   |");
        name.add("Izanagi Picaro            |");
        name.add("Naga                      |");
        name.add("Rakshasa                  |");
        name.add("Sui-ki                    |");
        name.add("Anzu                      |");
        name.add("Kin-ki                    |");
        name.add("Koh-i-Noor                |");
        name.add("Setanta                   |");
        name.add("Kaguya Picaro             |");
        name.add("Isis                      |");
        name.add("Lamia                     |");
        name.add("Take-Minakata             |");
        name.add("Orpheus                   |");
        name.add("Andras                    |");
        name.add("Clotho                    |");
        name.add("Tam Lin                   |");
        name.add("Choronzon                 |");
        name.add("Pisaca                    |");
        name.add("Principality              |");
        name.add("Orpheus Picaro            |");
        name.add("Ara Mitama                |");
        name.add("Neko Shogun               |");
        name.add("Orlov                     |");
        name.add("Ariadne                   |");
        name.add("Kurama Tengu              |");
        name.add("Zouchouten                |");
        name.add("Decarabia                 |");
        name.add("Lilim                     |");
        name.add("Mithra                    |");
        name.add("Mothman                   |");
        name.add("Anubis                    |");
        name.add("Thunderbird               |");
        name.add("Arahabaki                 |");
        name.add("Emperor's Amulet          |");
        name.add("Lachesis                  |");
        name.add("Kaiwan                    |");
        name.add("Thoth                     |");
        name.add("Belphegor                 |");
        name.add("Hell Biker                |");
        name.add("Legion                    |");
        name.add("White Rider               |");
        name.add("Atropos                   |");
        name.add("Mithras                   |");
        name.add("Unicorn                   |");
        name.add("Daisoujou                 |");
        name.add("Hariti                    |");
        name.add("Hope Diamond              |");
        name.add("Kikuri-Hime               |");
        name.add("Power                     |");
        name.add("Red Rider                 |");
        name.add("Hecatoncheires            |");
        name.add("Kumbhanda                 |");
        name.add("Kushimada                 |");
        name.add("Ose                       |");
        name.add("Ariadne Picaro            |");
        name.add("Girimehkala               |");
        name.add("Queen Mab                 |");
        name.add("Yurlungur                 |");
        name.add("Ananta                    |");
        name.add("Valkyrie                  |");
        name.add("Magatsu-Izanagi           |");
        name.add("Byakko                    |");
        name.add("Pazuzu                    |");
        name.add("Fortuna                   |");
        name.add("Athena                    |");
        name.add("Horus                     |");
        name.add("Narcissus                 |");
        name.add("Rangda                    |");
        name.add("Magatsu-Izangi Picaro     |");
        name.add("Bugs                      |");
        name.add("Koumokuten                |");
        name.add("Crystal Skull             |");
        name.add("Dakini                    |");
        name.add("Sarasvati                 |");
        name.add("Athena Picaro             |");
        name.add("Tsukiyomi                 |");
        name.add("Jatayu                    |");
        name.add("Seth                      |");
        name.add("Barong                    |");
        name.add("Garuda                    |");
        name.add("Mishaguji                 |");
        name.add("Norn                      |");
        name.add("Ganesha                   |");
        name.add("Skadi                     |");
        name.add("Okuninushi                |");
        name.add("Pale Rider                |");
        name.add("Cerberus                  |");
        name.add("Raja Naga                 |");
        name.add("Tsukiyomi Picaro          |");
        name.add("Parvati                   |");
        name.add("Titania                   |");
        name.add("Asterius                  |");
        name.add("Yatagarasu                |");
        name.add("Baphomet                  |");
        name.add("Melchizedek               |");
        name.add("Black Rider               |");
        name.add("Trumpeter                 |");
        name.add("Lilith                    |");
        name.add("Moloch                    |");
        name.add("Orichalcum                |");
        name.add("King Frost                |");
        name.add("Chernobog                 |");
        name.add("Seiryu                    |");
        name.add("Asterius Picaro           |");
        name.add("Forneus                   |");
        name.add("Kali                      |");
        name.add("Hanuman                   |");
        name.add("Thor                      |");
        name.add("Yamata-no-Orochi          |");
        name.add("Atavaka                   |");
        name.add("Thanatos                  |");
        name.add("Oberon                    |");
        name.add("Quetzalcoatl              |");
        name.add("Bishamonten               |");
        name.add("Black Frost               |");
        name.add("Dominion                  |");
        name.add("Vasuki                    |");
        name.add("Lakshmi                   |");
        name.add("Thanatos Picaro           |");
        name.add("Byakhee                   |");
        name.add("Loa                       |");
        name.add("Dionysus                  |");
        name.add("Mot                       |");
        name.add("Throne                    |");
        name.add("Macabre                   |");
        name.add("Mara                      |");
        name.add("Chimera                   |");
        name.add("Nebiros                   |");
        name.add("Abaddon                   |");
        name.add("Sandalphon                |");
        name.add("Asura                     |");
        name.add("Cu Chulainn               |");
        name.add("Kohryu                    |");
        name.add("Raoul                     |");
        name.add("Gabriel                   |");
        name.add("Scathach                  |");
        name.add("Raphael                   |");
        name.add("Sraosha                   |");
        name.add("Vohu Manah                |");
        name.add("Zaou-Gongen               |");
        name.add("Izanagi-no-Okami          |");
        name.add("Alilat                    |");
        name.add("Uriel                     |");
        name.add("Messiah                   |");
        name.add("Attis                     |");
        name.add("Baal                      |");
        name.add("Belial                    |");
        name.add("Shiva                     |");
        name.add("Alice                     |");
        name.add("Cybele                    |");
        name.add("Surt                      |");
        name.add("Vishnu                    |");
        name.add("Ardha                     |");
        name.add("Hastur                    |");
        name.add("Odin                      |");
        name.add("Siegfried                 |");
        name.add("Ishtar                    |");
        name.add("Mother Harlot             |");
        name.add("Fafnir                    |");
        name.add("Futsunushi                |");
        name.add("Beelzebub                 |");
        name.add("Michael                   |");
        name.add("Yoshitsune                |");
        name.add("Chi You                   |");
        name.add("Metatron                  |");
        name.add("Ongyo-Ki                  |");
        name.add("Izanagi-no-Okami Picaro   |");
        name.add("Mada                      |");
        name.add("Messiah Picaro            |");
        name.add("Satan                     |");
        name.add("Lucifer                   |");
        name.add("Maria                     |");
        name.add("Satanael                  |");
        ArrayList arcana = new ArrayList();
        arcana.add("Fool        |");
        arcana.add("Magician    |");
        arcana.add("Lovers      |");
        arcana.add("Chariot     |");
        arcana.add("Death       |");
        arcana.add("Hermit      |");
        arcana.add("Magician    |");
        arcana.add("Devil       |");
        arcana.add("Strength    |");
        arcana.add("Lovers      |");
        arcana.add("Priestess   |");
        arcana.add("Temperence  |");
        arcana.add("Moon        |");
        arcana.add("Fool        |");
        arcana.add("Justice     |");
        arcana.add("Hierophant  |");
        arcana.add("Hnaged      |");
        arcana.add("Hermit      |");
        arcana.add("Death       |");
        arcana.add("Emperor     |");
        arcana.add("Chariot     |");
        arcana.add("Priestess   |");
        arcana.add("Magician    |");
        arcana.add("Star        |");
        arcana.add("Temperence  |");
        arcana.add("Fool        |");
        arcana.add("Councillor  |");
        arcana.add("Moon        |");
        arcana.add("Lovers      |");
        arcana.add("Hermit      |");
        arcana.add("Fool        |");
        arcana.add("Justice     |");
        arcana.add("Hanged      |");
        arcana.add("Temperence  |");
        arcana.add("Empress     |");
        arcana.add("Strength    |");
        arcana.add("Emperor     |");
        arcana.add("Fool        |");
        arcana.add("Sun         |");
        arcana.add("Moon        |");
        arcana.add("Death       |");
        arcana.add("Magician    |");
        arcana.add("Hierophant  |");
        arcana.add("Hermit      |");
        arcana.add("Moon        |");
        arcana.add("Chariot     |");
        arcana.add("Devil       |");
        arcana.add("Lovers      |");
        arcana.add("Death       |");
        arcana.add("Strength    |");
        arcana.add("Fortune     |");
        arcana.add("Empress     |");
        arcana.add("Fool        |");
        arcana.add("Hanged      |");
        arcana.add("Faith       |");
        arcana.add("Temperence  |");
        arcana.add("Councillor  |");
        arcana.add("Star        |");
        arcana.add("Magician    |");
        arcana.add("Fool        |");
        arcana.add("Hermit      |");
        arcana.add("Strength    |");
        arcana.add("Moon        |");
        arcana.add("Hierophant  |");
        arcana.add("Chariot     |");
        arcana.add("Priestess   |");
        arcana.add("Emperor     |");
        arcana.add("Moon        |");
        arcana.add("Priestess   |");
        arcana.add("Empress     |");
        arcana.add("Hanged      |");
        arcana.add("Fool        |");
        arcana.add("Devil       |");
        arcana.add("Fortune     |");
        arcana.add("Faith       |");
        arcana.add("Magician    |");
        arcana.add("Death       |");
        arcana.add("Justice     |");
        arcana.add("Fool        |");
        arcana.add("Chariot     |");
        arcana.add("Star        |");
        arcana.add("Strength    |");
        arcana.add("Fortune     |");
        arcana.add("Hermit      |");
        arcana.add("Strength    |");
        arcana.add("Councillor  |");
        arcana.add("Devil       |");
        arcana.add("Temperence  |");
        arcana.add("Moon        |");
        arcana.add("Judgment    |");
        arcana.add("Sun         |");
        arcana.add("Hermit      |");
        arcana.add("Hanged      |");
        arcana.add("Fortune     |");
        arcana.add("Star        |");
        arcana.add("Emperor     |");
        arcana.add("Tower       |");
        arcana.add("Death       |");
        arcana.add("Fool        |");
        arcana.add("Chariot     |");
        arcana.add("Fortune     |");
        arcana.add("Sun         |");
        arcana.add("Faith       |");
        arcana.add("Hierophant  |");
        arcana.add("Empress     |");
        arcana.add("Death       |");
        arcana.add("Priestess   |");
        arcana.add("Justice     |");
        arcana.add("Tower       |");
        arcana.add("Hanged      |");
        arcana.add("Hermit      |");
        arcana.add("Lovers      |");
        arcana.add("Fool        |");
        arcana.add("Foertune    |");
        arcana.add("Moon        |");
        arcana.add("Magician    |");
        arcana.add("Sun         |");
        arcana.add("Councillor  |");
        arcana.add("Strength    |");
        arcana.add("Tower       |");
        arcana.add("Temperence  |");
        arcana.add("Devil       |");
        arcana.add("Fortune     |");
        arcana.add("Chariot     |");
        arcana.add("Sun         |");
        arcana.add("Lovers      |");
        arcana.add("Magician    |");
        arcana.add("Tower       |");
        arcana.add("Fool        |");
        arcana.add("Hermit      |");
        arcana.add("Fool        |");
        arcana.add("Empress     |");
        arcana.add("Priestess   |");
        arcana.add("Chariot     |");
        arcana.add("Moon        |");
        arcana.add("Hanged      |");
        arcana.add("Tower       |");
        arcana.add("Emperor     |");
        arcana.add("Star        |");
        arcana.add("Hierophant  |");
        arcana.add("Fortune     |");
        arcana.add("Sun         |");
        arcana.add("Pirestss    |");
        arcana.add("Faith       |");
        arcana.add("Death       |");
        arcana.add("Chariot     |");
        arcana.add("Temperence  |");
        arcana.add("Moon        |");
        arcana.add("Lovers      |");
        arcana.add("Empress     |");
        arcana.add("Fortune     |");
        arcana.add("Councillor  |");
        arcana.add("Devil       |");
        arcana.add("Justice     |");
        arcana.add("Tower       |");
        arcana.add("Judgement   |");
        arcana.add("Moon        |");
        arcana.add("Hanged      |");
        arcana.add("Faith       |");
        arcana.add("Emperor     |");
        arcana.add("Death       |");
        arcana.add("Councillor  |");
        arcana.add("Fortune     |");
        arcana.add("Magician    |");
        arcana.add("Empress     |");
        arcana.add("Strength    |");
        arcana.add("Chariot     |");
        arcana.add("Judgement   |");
        arcana.add("Faith       |");
        arcana.add("Death       |");
        arcana.add("Emperor     |");
        arcana.add("Sun         |");
        arcana.add("Hierophant  |");
        arcana.add("Fool        |");
        arcana.add("Justice     |");
        arcana.add("Star        |");
        arcana.add("Fortune     |");
        arcana.add("Death       |");
        arcana.add("Moon        |");
        arcana.add("Hermit      |");
        arcana.add("Councillor  |");
        arcana.add("Death       |");
        arcana.add("Justice     |");
        arcana.add("Hanged      |");
        arcana.add("Tower       |");
        arcana.add("Strength    |");
        arcana.add("Devil       |");
        arcana.add("Judgement   |");
        arcana.add("Moon        |");
        arcana.add("Sun         |");
        arcana.add("Fsith       |");
        arcana.add("Hierophant  |");
        arcana.add("Fool        |");
        arcana.add("Temperence  |");
        arcana.add("Priestess   |");
        arcana.add("Lovers      |");
        arcana.add("Star        |");
        arcana.add("Councillor  |");
        arcana.add("Strength    |");
        arcana.add("World       |");
        arcana.add("Empress     |");
        arcana.add("Justice     |");
        arcana.add("Judgment    |");
        arcana.add("Hanged      |");
        arcana.add("Emperor     |");
        arcana.add("Devil       |");
        arcana.add("Judgement   |");
        arcana.add("Death       |");
        arcana.add("Priestess   |");
        arcana.add("Magician    |");
        arcana.add("Fool        |");
        arcana.add("Temperence  |");
        arcana.add("Star        |");
        arcana.add("Emperor     |");
        arcana.add("Faith       |");
        arcana.add("Lovers      |");
        arcana.add("Empress     |");
        arcana.add("Hermit      |");
        arcana.add("Magician    |");
        arcana.add("Devil       |");
        arcana.add("Judgment     |");
        arcana.add("Tower       |");
        arcana.add("Chariot     |");
        arcana.add("Justice     |");
        arcana.add("Hermit      |");
        arcana.add("World       |");
        arcana.add("Tower       |");
        arcana.add("Judgement   |");
        arcana.add("Judgement   |");
        arcana.add("Star        |");
        arcana.add("Faith       |");
        arcana.add("Fool        |");
        System.out.println("  Lv. Persona                     Arcana");
        for (int i = 0; i < nivel.size(); i++) {
            System.out.println((i+1)+".|"+nivel.get(i)+"||"+name.get(i)+"|"+arcana.get(i));
        }
    }
    
}
